### ISSUE TITLE
How to fix issues in assay_types.tsv?

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/search-schema#8]
The assay types document has a few issues that should be fixed (https://github.com/hubmapconsortium/search-schema/blob/master/data/definitions/enums/assay_types.tsv):

Typos in description:
Multiplexex Immunofluorescence Microscopy -> Multiplexed Immunofluorescence Microscopy

Inconsistent naming:
ATACseq-bulk -> bulk-ATACseq
bulk-RNA -> bulk-RNAseq
scRNA-Seq-10x -> scRNAseq-10x
seqFish -> seqFISH
LC-MS-untargeted -> Untargeted-LC-MS `(to match Targeted-Shotgun-LC-MS)`

**Comment by mccalluc** [comment]
- Will fix the one typo.
- Codes were given to me by Bill. It has been a struggle to get adherence to _any_ standardized codes, so I'm very reluctant to move the target. We will be changing these for display, so unless you find small internal variations abhorrent, I don't think this should be a focus.

**Comment by ngehlenborg** [comment]
Ok, sounds good. I posed it as a question because I wasn’t sure whether we have any control over the first column.

On Jun 4, 2020, at 3:53 PM, Chuck McCallum <notifications@github.com> wrote:

﻿

  *   Will fix the one typo.
  *   Codes were given to me by Bill. It has been a struggle to get adherence to any standardized codes, so I'm very reluctant to move the target. We will be changing these for display, so unless you find small internal variations abhorrent, I don't think this should be a focus.
